#ifndef SCREEN_INTERACTION_CONTROLLER_KEYBOARD
#define SCREEN_INTERACTION_CONTROLLER_KEYBOARD

enum Keyboard {
    ENTER = 13,
    ESC = 27,
    PAGE_UP = 73,
    PAGE_DOWN = 81,
    HOME = 71,
    END = 79,
    KEY_LEFT = 75,
    KEY_UP = 72,
    KEY_RIGHT = 77,
    KEY_DOWN = 80
}

#endif
